#pragma once

enum Authority
{
    WORKER,
    CONTACTWORKER,
    ONLINESUPPORTWORKER,
    SALESWORKER,

    WORKERDIRECTOR,
    CONTACTWORKERDIRECTOR,
    ONLINESUPPORTWORKERDIRECTOR,
    SALESWORKERDIRECTOR,
    MODERATOR,
    GOVERNOR,
    ADMIN
};